// <auto-generated />
using System;
using Futebol.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Futebol.Api.Migrations
{
    [DbContext(typeof(FutebolDbContext))]
    [Migration("20251226092950_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("Futebol.Api.Domain.Jogador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("Destaque")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrganizadorId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Peso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Posicao")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrganizadorId");

                    b.ToTable("Jogadores", (string)null);
                });

            modelBuilder.Entity("Futebol.Api.Domain.Organizador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Organizadores", (string)null);
                });

            modelBuilder.Entity("Futebol.Api.Domain.Partida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GolsCasa")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GolsVisitante")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SorteioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeCasaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimeVisitanteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Partidas", t =>
                        {
                            t.HasCheckConstraint("CK_Partida_Times_Diferentes", "TimeCasaId <> TimeVisitanteId");
                        });
                });

            modelBuilder.Entity("Futebol.Api.Domain.Sorteio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizadorId")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantidadeTimes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sorteios");
                });

            modelBuilder.Entity("Futebol.Api.Domain.Time", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SorteioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SorteioId");

                    b.ToTable("Times");
                });

            modelBuilder.Entity("Futebol.Api.Domain.TimeJogador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("JogadorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JogadorId");

                    b.HasIndex("TimeId", "JogadorId")
                        .IsUnique();

                    b.ToTable("TimeJogadores");
                });

            modelBuilder.Entity("Futebol.Api.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Futebol.Api.Domain.Jogador", b =>
                {
                    b.HasOne("Futebol.Api.Domain.Organizador", "Organizador")
                        .WithMany("Jogadores")
                        .HasForeignKey("OrganizadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organizador");
                });

            modelBuilder.Entity("Futebol.Api.Domain.Organizador", b =>
                {
                    b.HasOne("Futebol.Api.Domain.User", "User")
                        .WithMany("Organizadores")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Futebol.Api.Domain.Time", b =>
                {
                    b.HasOne("Futebol.Api.Domain.Sorteio", "Sorteio")
                        .WithMany("Times")
                        .HasForeignKey("SorteioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sorteio");
                });

            modelBuilder.Entity("Futebol.Api.Domain.TimeJogador", b =>
                {
                    b.HasOne("Futebol.Api.Domain.Jogador", "Jogador")
                        .WithMany("Times")
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Futebol.Api.Domain.Time", "Time")
                        .WithMany("Jogadores")
                        .HasForeignKey("TimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogador");

                    b.Navigation("Time");
                });

            modelBuilder.Entity("Futebol.Api.Domain.Jogador", b =>
                {
                    b.Navigation("Times");
                });

            modelBuilder.Entity("Futebol.Api.Domain.Organizador", b =>
                {
                    b.Navigation("Jogadores");
                });

            modelBuilder.Entity("Futebol.Api.Domain.Sorteio", b =>
                {
                    b.Navigation("Times");
                });

            modelBuilder.Entity("Futebol.Api.Domain.Time", b =>
                {
                    b.Navigation("Jogadores");
                });

            modelBuilder.Entity("Futebol.Api.Domain.User", b =>
                {
                    b.Navigation("Organizadores");
                });
#pragma warning restore 612, 618
        }
    }
}
